scoutman_photo/gallery/urls.py
# encoding: utf-8
from django.conf.urls import include, url
from django.views.generic import TemplateView
from . import views

urlpatterns = [
	url(r'^(?P<slug>[-_\w]+)/$', views.DetailView.as_view(), name='category'),
]

scoutman_photo/home/urls.py
# encoding: utf-8
from django.conf.urls import include, url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='home'),
]

scoutman_photo/scoutman_photo/urls.py
# encoding: utf-8
from django.conf.urls import include, url
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
#from django.contrib.sitemaps import FlatPageSitemap, GenericSitemap

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
	url(r'^', include('home.urls', namespace='home')),
	url(r'^ueber-mich/$', TemplateView.as_view(template_name='about/about.html'), name='ueber-mich'),
	url(r'^galerie/', include('gallery.urls', namespace='gallery')),
	url(r'^intern/', include(admin.site.urls))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scoutman_photo/upload/urls.py
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = patterns('',
    url(r'^$', views.upload_file, name='upload_file'),
)

scoutman_photo/gallery/models.py
# encoding: utf-8
from os import remove, makedirs, rename, rmdir, listdir
from os.path import basename, exists
from PIL import Image, ImageOps
from django.conf import settings
from django.db import models
from django.utils.text import slugify
from django.core.files.move import file_move_safe

class Category(models.Model):
	name = models.CharField(max_length=255)
	description = models.CharField(max_length=255, blank=True)
	slug = models.SlugField()
	active = models.BooleanField(default=True)

	def __unicode__(self):
		return self.name

	def save(self, *args, **kwargs):
		dir_category_root = '%s/gallery/%s' % (settings.MEDIA_ROOT, slugify(self.slug))
		if not exists(dir_category_root):
			makedirs(dir_category_root)		

		super(Category, self).save(*args, **kwargs)

	def delete(self, *args, **kwargs):
		dir_category_root = '%s/gallery/%s' % (settings.MEDIA_ROOT, slugify(self.slug))
		files = listdir(dir_category_root)
		
		if len(files) == 0:
			rmdir(dir_category_root)		

		super(Category, self).delete(*args, **kwargs)

		
class Picture(models.Model):

	def upload_path(self, filename):
		filename = basename(filename)
		filename = filename.split('.')
		extension = filename.pop()
		name = ''.join(filename)
		return 'gallery/%s/%s.%s' % (self.category.slug, slugify(name), extension)
	
	category = models.ForeignKey(Category)
	image = models.ImageField(upload_to=upload_path)
	thumb = models.ImageField(upload_to=upload_path, blank=True, editable=False)
	title = models.CharField(max_length=255, blank=True)
	pub_date = models.DateTimeField(auto_now = False, auto_now_add = True)
	
	class Meta:
		ordering = ['-pub_date']
		
	def __unicode__(self):
		return unicode(self.image)
	
	def create_thumbnail(self):			
		image = basename(self.image.name)
		image = image.split('.')
		extension = image.pop()
		name = ''.join(image)
		
		filename_thumb_root = '%s/gallery/%s/%s.thumb.%s' % (settings.MEDIA_ROOT, self.category.slug, slugify(name), extension)
		filename_thumb = 'gallery/%s/%s.thumb.%s' % (self.category.slug, slugify(name), extension)
		
		self.thumb = filename_thumb
		
		size = int(settings.SITE_CONFIG['thumb_width']), int(settings.SITE_CONFIG['thumb_height'])
		tmp_img = Image.open(self.image)
		thumb = ImageOps.fit(tmp_img, size, Image.ANTIALIAS)
		thumb.save(filename_thumb_root)
		
	
	def save(self, *args, **kwargs):
	
		if self.pk is not None:
			orig = Picture.objects.get(pk=self.pk)
			
			if orig.image != self.image:
				remove(orig.image.path)
				remove(orig.thumb.path)
			
			if orig.category != self.category:
				image = basename(orig.image.path)
				thumb = basename(orig.thumb.path)
				
				image_root = '%s/gallery/%s/%s' % (settings.MEDIA_ROOT, self.category.slug, image)
				thumb_root = '%s/gallery/%s/%s' % (settings.MEDIA_ROOT, self.category.slug, thumb)
				
				file_move_safe(orig.image.path, image_root)
				file_move_safe(orig.thumb.path, thumb_root)
				
				self.image = 'gallery/%s/%s' % (self.category.slug, image)
				self.thumb = 'gallery/%s/%s' % (self.category.slug, thumb)
				
		else:		
			self.create_thumbnail()
			
		super(Picture, self).save(*args, **kwargs)
		
	def delete(self, *args, **kwargs):
		remove(self.image.path)
		remove(self.thumb.path)
		super(Picture, self).delete(*args, **kwargs)
		
	def thumb_path(self):
		thumb = self.thumb.url
		return '<img width="100" height="100" src="%s" />' % (str(thumb))
	
	thumb_path.short_description = 'Thumbnail'
	thumb_path.allow_tags = True

scoutman_photo/upload/models.py
# -*- coding: utf-8 -*-
from django.db import models

class Document(models.Model):
	docfile = models.FileField(upload_to='documents')

scoutman_photo/upload/forms.py
from django import forms

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file  = forms.FileField()

scoutman_photo/gallery/views.py
# encoding: utf-8
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from .models import Category, Picture


class DetailView(generic.DetailView):
	model = Category
	template_name = 'gallery/gallery.html'

	def get_context_data(self, **kwargs):
		context = super(DetailView, self).get_context_data(**kwargs)
		return context

scoutman_photo/home/views.py
# encoding: utf-8
import os, random
from django.shortcuts import render, get_object_or_404
from django.conf import settings

def index(request):

	slider_dir = "%s/slider" % (settings.MEDIA_ROOT)

	os.chdir(slider_dir)
	i = 0
	img_list = {}
	
	for file in os.listdir("."):
		if file.split('.')[-1].lower() in ["png", "jpg", "jpeg"] :
			img_list[i] = "slider/%s" % file
			i += 1
	
	r = random.choice(list(img_list))

	return render(request, 'home/home.html', {'slider_img' : img_list[r]})

scoutman_photo/upload/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.core.urlresolvers import reverse

from django import forms
from .models import Document


"""
def upload_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            handle_uploaded_file(request.FILES['file'])
            return HttpResponseRedirect('/success/url/')
    else:
        form = UploadFileForm()
    return render(request, 'upload/upload.html', {'form': form})
"""


def upload_file(request):
	if request.method == 'POST':
		print('POST')
		form = UploadFileForm(request.POST, request.FILES)
		print('valid')
		if form.is_valid():
			# file is saved
			print('save')
			newdoc = Document(docfile = request.FILES['file'])
			newdoc.save()			
			#form.save()
			print('return')
			return HttpResponseRedirect(reverse('upload:upload_file'))
	else:
		form = UploadFileForm()
		return render(request, 'upload/upload.html', {'form': form})	


class UploadFileForm(forms.Form):
	#title = forms.CharField(max_length=50)
	file  = forms.FileField()

scoutman_photo/templates/about/about.html
{% extends "base.html" %}
{% load staticfiles %}

{% block site_name %}Über mich | {{block.super}}{% endblock %}

{% block site_description %}Sascha Mlakar im Detail - Fototasche, Kontakt und weitere Links{% endblock %}

{% block nav_about_active %}nav_active{% endblock %}

{% block content %}
	<article>
		<div class="content">
			<header>
				<h1>Über mich</h1>
			</header>
			Sascha Mlakar<br />
			Seit 2008 mit einer DSLR unterwegs. Hauptsächlich beschäftige ich mich mit der Natur- und Landschaftsfotografie. Warum? Berge können nicht blöd schauen.
			<br /><br />
			
			<h2>Fototasche</h2>
			Canon EOS 50D | Canon EOS 5D III<br />
			Canon 50mm f/1.4 | Canon 16-35mm f/2.8L | Canon 24-105mm f/4L | Canon 70-200mm f/2.8L 
			<br /><br />
			Olympus E-M10 MARK II<br />
			M.ZUIKO DIGITAL 17mm f/1.8
			<br /><br />
			
			<h2>Kontakt</h2>
			mail (at) scoutman (dot) at
			<br /><br />
			
			<h2>Links</h2>
			<a href="http://www.facebook.com/SaschaMlakarPhotography">Facebook</a> | <a href="https://www.instagram.com/scoutman_at">Instagram</a> | <a href="http://500px.com/scoutman">500px</a> | <a href="http://www.fotocommunity.de/fotograf/scoutman/1855173">fotocommunity</a>
			<br /><br /><br />

			<div class="portrait_container">
				<img alt="Portrait Sascha Mlakar" src="{% static 'img/portrait.png' %}" />
			<div>

		</div>
	</article>
{% endblock content %}

scoutman_photo/templates/base.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html>
<head>
<title>{% block site_name %}{{config.site_name}}{% endblock %}</title>

<meta charset="utf-8">
<meta name="description" content="{% block site_description %}Portfolio von Sascha Mlakar Photography | Natur- und Landschaftsfotografie{% endblock %}">
<meta name="author" content="Sascha Mlakar">
<meta name="keywords" content="photography, sascha mlakar, fotografie, landscape, landschaft, landschaftsfotografie, natur">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="theme-color" content="#2F2F31">

<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
<link rel="stylesheet" href="{% static 'css/scoutman.css' %}" type="text/css" media="screen" />
<link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
{% block css %}{% endblock %}
<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" media="screen" rel="stylesheet" type="text/css" />
<link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700" rel="stylesheet">
<link rel="apple-touch-icon" href="{% static 'img/ente-128px.png' %}" />

</head>

<body>
	
	<header>
		<div class="header">
			<a href="{% url 'home:home' %}"><img width="300" src="{% static 'img/Unterschrift_Sascha_Photography.png' %}" /></a>
		</div>
	</header>

	<nav>
		<ul class="nav">
							
			<li>
				<a class="{% block nav_home_active %}{% endblock %}" href="{% url 'home:home' %}">Home</a>
			</li>
			
			<li>
				<span class="{% block nav_gallery_active %}{% endblock %}">Galerie</span>
				<ul>
					{% for category in category_list %}
						<li>
							<a href="{% url 'gallery:category' category.slug %}">{{ category.name }}</a>
						</li>
					{% endfor %}
				</ul>
			</li>

			<li>
				<a class="{% block nav_about_active %}{% endblock %}" href="{% url 'ueber-mich' %}">Über mich</a>
			</li>

		</ul>
	</nav>
	
	<div style="clear:both;"></div>
	
	{% block content %}{% endblock %}
	
	<footer>

		<a href="http://www.facebook.com/SaschaMlakarPhotography"><i class="fa fa-facebook-official fa-lg" aria-hidden="true"></i></a>
		<a href="https://www.instagram.com/scoutman_at"><i class="fa fa-instagram fa-lg" aria-hidden="true"></i></a>
		<a href="http://500px.com/scoutman"><i class="fa fa-500px fa-lg" aria-hidden="true"></i></a>

	</footer>
	
	<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
	{% block javascript %}{% endblock %}
	<script type="text/javascript" src="{% static 'fancybox/lib/jquery.mousewheel-3.0.6.pack.js' %}"></script>
	<script type="text/javascript" src="{% static 'fancybox/source/jquery.fancybox.pack.js' %}"></script>	
	<script type="text/javascript" src="{% static 'js/scoutman.js' %}"></script>
	
	<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
		  ga('create', 'UA-23788584-2', 'scoutman.at');
		  ga('send', 'pageview');
	</script>
	
</body>
</html>

scoutman_photo/templates/blog/blog.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
	<div class="content">
		<h1>Test Überschrift</h1>
		<h2>Test Überschrift</h2>

		
		test as asd dasd sadas d<br />
		test as asd dasd sadas d<br />
		test as asd dasd sadas d<br />
		test as asd dasd sadas d<br />
		test as asd dasd sadas d<br />
		test as asd <a href="">ich bin ein link</a> dasd sadas d<br />
		test as asd dasd sadas d<br />
		test as asd dasd sadas d<br />
		test as asd dasd sadas d<br />
		test as asd dasd sadas d<br />
		test as asd dasd sadas d<br />
		
	</div>

{% endblock %}

scoutman_photo/templates/gallery/gallery.html
{% extends "base.html" %}
{% load staticfiles %}

{% block site_name %}Galerie {{category}} | {{block.super}}{% endblock %}

{% block site_description %}Eine Übersicht der Galerie {{category}}{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'fancybox/source/jquery.fancybox.css' %}" type="text/css" media="screen" />
{% endblock css %}

{% block nav_gallery_active %}nav_active{% endblock %}

{% block content %}
	<article>
		<div class="gallery">
			<header>
				<h1>{{category}}</h1>
			</header>
			
			<div class="content_gallery">
		
				{% for img in category.picture_set.all %}
					<div class="picture-container">
						<a title="{{img.title}}" class="fancybox" rel="{{category.slug}}" href="{{ MEDIA_URL }}{{img.image}}">
							<img class="picture" src="{{ MEDIA_URL }}{{img.thumb}}" alt="" />
						</a>
					</div>
				{% endfor %}
				
			</div>
		</div>
	</article>
{% endblock content %}

{% block javascript %}

{% endblock javascript %}

scoutman_photo/templates/home/home - Kopie.html
{% extends "base.html" %}
{% load staticfiles %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/nivo-slider.css' %}" type="text/css" media="screen" />
<link rel="stylesheet" href="{% static 'css/nivo-slider-default.css' %}" type="text/css" media="screen" />
{% endblock css %}

{% block nav_home_active %}nav_active{% endblock %}

{% block content %}
	<article>
		<div class="slider-wrapper theme-default">
			<div id="slider" class="nivoSlider">
				{% for key, name in img_list.items %}
					<img height="{{config.home_slider_height}}" width="{{config.home_slider_width}}" src="{{ MEDIA_URL }}{{name}}" data-thumb="{{ MEDIA_URL }}{{name}}" />
				{% endfor %}
			</div>
		</div>
	</article>
{% endblock content %}

{% block javascript %}

{% endblock javascript %}

scoutman_photo/templates/home/home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block nav_home_active %}nav_active{% endblock %}

{% block content %}
	
	<div class="slider_container" style="background-image: url('{{ MEDIA_URL }}{{ slider_img }}');">
		 
	</div>
	
{% endblock content %}

{% block javascript %}

{% endblock javascript %}

scoutman_photo/templates/upload/upload.html
{% extends "base.html" %}


{% block upload %}

<div class="content">
	<form action="{% url 'upload:upload_file' %}" method="post" enctype="multipart/form-data">

	{% csrf_token %}
	
	{{form.file}}
	{{form.file}}

	<button type="submit">Speichern</button>
	</form>
	
</div>


{% endblock %}